/**
 * Pulls content out of Sanity at BUILD time and writes it into
 * src/content/generated/. Nothing here runs in the browser — visitors never
 * talk to Sanity, so the site keeps exactly the runtime dependencies it has
 * today, which is none.
 *
 * Run automatically by `npm run build` (see the `prebuild` script).
 *
 * Fail-open by design:
 *   - Sanity unreachable  -> warn, keep the committed JSON, build succeeds.
 *   - Sanity returns junk -> fail the build loudly rather than ship it.
 *   - A page not yet in Sanity -> writes null; the component uses its
 *     built-in copy, so half-migrated is a safe state.
 *
 * The generated files are COMMITTED. That is deliberate: the site still
 * builds if the Sanity account lapses, `npm start` works with no network,
 * and every publish leaves a reviewable diff in git.
 */
import { writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const PROJECT_ID = "bj87pb9z";
const DATASET = "production";
const API_VERSION = "2024-01-01";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = path.join(ROOT, "src", "content", "generated");
const IMG_DIR = path.join(ROOT, "src", "assets", "generated");

/**
 * Images published in Sanity are DOWNLOADED here at build time and emitted as
 * real `import` statements, so webpack bundles them exactly like any other
 * asset: content-hashed filename, immutable cache header, served from the same
 * origin as the site. A visitor's browser never contacts Sanity.
 *
 * Sanity asset IDs are content hashes, so a filename only changes when the
 * picture does — an unchanged publish produces no git diff.
 */
const downloads = new Map(); // key -> { url, file }

function registerImage(url, width) {
  if (!url || !url.startsWith("http")) return url;
  const assetId = url.split("/").pop().split(".")[0];
  const key = `${assetId}-${width}`;
  downloads.set(key, {
    url: `${url}?w=${width}&fm=webp&q=78&fit=max`,
    file: `${key}.webp`,
  });
  return key; // the component resolves this through the generated image map
}

/**
 * Gallery photos are NOT baked. There can be dozens per event and hundreds
 * overall — committing those binaries would grow the repo without bound and
 * they cannot be removed from git history later. They sit below the fold and
 * load lazily, so a CDN round trip is the right trade. Cover photos and hero
 * banners stay baked because they are few, fixed, and above the fold.
 */
function cdnUrl(url, width) {
  if (!url || !url.startsWith("http")) return url;
  return `${url}?w=${width}&fm=webp&q=78&fit=max&auto=format`;
}

async function downloadImages() {
  if (downloads.size === 0) {
    await writeFile(
      path.join(OUT_DIR, "images.js"),
      "// No CMS images published yet.\nexport const IMAGES = {};\n",
    );
    return;
  }
  await mkdir(IMG_DIR, { recursive: true });

  let fetched = 0;
  for (const [key, { url, file }] of downloads) {
    const dest = path.join(IMG_DIR, file);
    if (existsSync(dest)) continue; // content-hashed: same name means same bytes
    const res = await fetch(url, { signal: AbortSignal.timeout(30000) });
    if (!res.ok) throw new Error(`image ${key}: HTTP ${res.status}`);
    await writeFile(dest, Buffer.from(await res.arrayBuffer()));
    fetched++;
  }

  const keys = [...downloads.keys()];
  const body =
    "// Generated by scripts/fetch-content.mjs — do not edit.\n" +
    "// Real imports, so webpack fingerprints and bundles these like any asset.\n" +
    keys.map((k, i) => `import i${i} from "../../assets/generated/${downloads.get(k).file}";`).join("\n") +
    "\n\nexport const IMAGES = {\n" +
    keys.map((k, i) => `  ${JSON.stringify(k)}: i${i},`).join("\n") +
    "\n};\n";
  await writeFile(path.join(OUT_DIR, "images.js"), body);
  console.log(`✓ Images: ${downloads.size} bundled (${fetched} newly downloaded)`);
}

/** One entry per generated file. `check` throws on content we refuse to ship. */
const SOURCES = [
  {
    file: "news.json",
    label: "News & events",
    query: `{"news": *[_type == "newsEvent" && defined(slug.current)] | order(date desc) {
      "id": slug.current, name, subheading, date, time, desc, link, body,
      "image": image.asset->url,
      "imageAlt": coalesce(image.alt, name),
      "gallery": gallery[]{ "url": asset->url, alt, caption }
    }}`,
    empty: { news: [] },
    check: (d) => {
      if (!Array.isArray(d.news)) throw new Error("`news` is not an array");
      d.news.forEach((n, i) => {
        for (const f of ["id", "name", "date", "desc", "image"]) {
          if (!n[f]) throw new Error(`news[${i}] is missing "${f}"`);
        }
        if (!/^\d{4}-\d{2}-\d{2}$/.test(n.date)) {
          throw new Error(`news[${i}].date is not YYYY-MM-DD: ${n.date}`);
        }
        // Cover photo: baked into the build (cards + home strip, above the fold).
        n.image = registerImage(n.image, 900);
        // Gallery: served from Sanity's CDN, at two sizes.
        n.gallery = (n.gallery || [])
          .filter((g) => g.url)
          .map((g) => ({
            full: cdnUrl(g.url, 1600),
            thumb: cdnUrl(g.url, 400),
            alt: g.alt || n.name,
            caption: g.caption || "",
          }));
      });
    },
  },
  {
    file: "footer.json",
    label: "Footer & contact",
    query: `{"page": *[_id == "footer"][0]{
      phone, email, address, copyrightName,
      socials[]{platform, url},
      usefulLinks[]{title, link},
      updateLinks[]{title, link},
      legalLinks[]{title, link}
    }}`,
    empty: { page: null },
    check: (d) => {
      if (!d.page) return;
      for (const f of ["phone", "email", "address", "copyrightName"]) {
        if (!d.page[f]) throw new Error(`footer is missing "${f}"`);
      }
      (d.page.socials || []).forEach((x, i) => {
        if (!x.platform || !x.url) throw new Error(`socials[${i}] is incomplete`);
      });
    },
  },
  {
    file: "privacy.json",
    label: "Privacy policy",
    query: `{"page": *[_id == "privacyPolicy"][0]{
      heading, lastUpdated, sections[]{heading, body}
    }}`,
    empty: { page: null },
    check: (d) => {
      if (!d.page) return;
      if (!d.page.heading || !d.page.lastUpdated) {
        throw new Error("privacy policy is missing a heading or date");
      }
      if (!Array.isArray(d.page.sections) || d.page.sections.length === 0) {
        throw new Error("privacy policy has no sections");
      }
      d.page.sections.forEach((x, i) => {
        if (!x.heading || !x.body) throw new Error(`privacy section ${i} is incomplete`);
      });
    },
  },
  {
    file: "home.json",
    label: "Home page",
    query: `{"page": *[_id == "homePage"][0]{
      heroSlides[]{
        "image": image.asset->url,
        "mobileImage": mobileImage.asset->url,
        alt, caption
      },
      bannerText, welcomeHeading, welcomeTagline, welcomeBody,
      facilities[]{name},
      expertiseHeading, expertise[]{heading, paragraph, listItems, subItems[]{subHeading, paragraph}, link},
      statsHeading, stats[]{value, label},
      feedbackHeading, reviews[]{name, profession, reviewDesc, "photo": photo.asset->url}
    }}`,
    empty: { page: null },
    check: (d) => {
      if (!d.page) return;
      // Slides not authored yet -> the component keeps its built-in banners.
      (d.page.heroSlides || []).forEach((s, i) => {
        if (!s.image) throw new Error(`heroSlides[${i}] has no photo`);
        if (!s.alt) throw new Error(`heroSlides[${i}] has no description`);
        s.mobileImage = registerImage(s.mobileImage || s.image, 900);
        s.image = registerImage(s.image, 1800);
      });
      for (const f of ["welcomeHeading", "welcomeBody", "facilities", "expertise", "stats", "reviews"]) {
        if (!d.page[f]) throw new Error(`home page is missing "${f}"`);
      }
      // Testimonial photos are optional; bake the ones that exist.
      (d.page.reviews || []).forEach((r) => {
        if (r.photo) r.photo = registerImage(r.photo, 200);
      });
      if (d.page.stats.length !== 3) throw new Error("home page needs exactly 3 numbers");
      if (d.page.expertise.length !== 3) throw new Error("home page needs exactly 3 expertise cards");
    },
  },
  {
    file: "about.json",
    label: "About page",
    query: `{"page": *[_id == "aboutPage"][0]{
      introHeading, introQuote, introBody,
      historyHeading, historyBody,
      missionHeading, missionBody, visionHeading, visionBody,
      whyHeading, whyPoints[]{title, desc}
    }}`,
    empty: { page: null },
    check: (d) => {
      if (!d.page) return;
      for (const f of ["introHeading", "introBody", "historyBody", "missionBody", "whyPoints"]) {
        if (!d.page[f]) throw new Error(`about page is missing "${f}"`);
      }
      if (d.page.whyPoints.length !== 3) throw new Error("about page needs exactly 3 reasons");
    },
  },
  {
    file: "infrastructure.json",
    label: "Infrastructure page",
    query: `{"page": *[_id == "infrastructurePage"][0]{
      introHeading, introBody,
      labsHeading, laboratories[]{name, desc},
      commonFacilitiesHeading, commonFacilities[]{title, desc},
      sportsHeading, sports[]{name, desc},
      classroomsHeading, classroomsIntro, classroomFeatures
    }}`,
    empty: { page: null },
    check: (d) => {
      if (!d.page) return;
      for (const f of ["introHeading", "laboratories", "commonFacilities", "sports", "classroomFeatures"]) {
        if (!d.page[f]) throw new Error(`infrastructure page is missing "${f}"`);
      }
      if (d.page.sports.length < 2) throw new Error("infrastructure needs at least 2 sports facilities");
      if (d.page.laboratories.length < 2) throw new Error("infrastructure needs at least 2 laboratories");
    },
  },
  {
    file: "academics.json",
    label: "Academics page",
    query: `{"page": *[_id == "academicsPage"][0]{
      introHeading, introSubheading, introBody,
      extracurricularsHeading, extracurricularsSubheading, extracurricularsIntro,
      extracurriculars[]{icon, title, desc},
      electivesHeading, electivesSubheading, electivesTagline, electivesIntro,
      electives[]{title, subtitle, desc},
      approachHeading, approachSubheading, approachIntro,
      approachFeatures[]{icon, title, desc}
    }}`,
    empty: { page: null },
    check: (d) => {
      if (!d.page) return;
      for (const f of ["introHeading", "introBody", "extracurriculars", "electives", "approachFeatures"]) {
        if (!d.page[f]) throw new Error(`academics page is missing "${f}"`);
      }
      if (d.page.approachFeatures.length !== 6) {
        throw new Error("academics page needs exactly 6 approach features");
      }
    },
  },
  {
    file: "contact.json",
    label: "Contact page",
    query: `{"page": *[_id == "contactPage"][0]{
      introBody, imageHeading, imageCtaLabel,
      address, officeHours,
      formHeading, formSubheading, formIntro, programs,
      successMessage, errorMessage
    }}`,
    empty: { page: null },
    check: (d) => {
      if (!d.page) return;
      for (const f of ["introBody", "imageHeading", "address", "officeHours", "formHeading"]) {
        if (!d.page[f]) throw new Error(`contact page is missing "${f}"`);
      }
      if (!Array.isArray(d.page.programs) || d.page.programs.length === 0) {
        throw new Error("contact page has no programmes");
      }
    },
  },
  {
    file: "admissions.json",
    label: "Admissions page",
    query: `{"page": *[_id == "admissionsPage"][0]{
      introHeading, introBody,
      applyHeading, applyBody, applyCtaLabel, applyCtaMode, applyCtaUrl,
      timeline[]{name, desc}
    }}`,
    empty: { page: null },
    check: (d) => {
      if (d.page === null || d.page === undefined) return; // not authored yet
      for (const f of ["introHeading", "introBody", "applyHeading", "applyBody"]) {
        if (!d.page[f]) throw new Error(`admissions page is missing "${f}"`);
      }
      if (!Array.isArray(d.page.timeline) || d.page.timeline.length === 0) {
        throw new Error("admissions page has no timeline steps");
      }
      d.page.timeline.forEach((s, i) => {
        if (!s.name || !s.desc) throw new Error(`timeline[${i}] is incomplete`);
      });
    },
  },
];

// Deliberately the UNCACHED api host, not apicdn. This runs once per build,
// triggered by a publish webhook — a cached response would hand the build
// pre-publish content and silently deploy stale copy.
const endpoint = (query) =>
  `https://${PROJECT_ID}.api.sanity.io/v${API_VERSION}/data/query/${DATASET}` +
  `?query=${encodeURIComponent(query)}`;

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  let reachable = true;

  for (const src of SOURCES) {
    const out = path.join(OUT_DIR, src.file);

    let result;
    try {
      const res = await fetch(endpoint(src.query), {
        signal: AbortSignal.timeout(20000),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
      result = (await res.json()).result;
    } catch (err) {
      reachable = false;
      console.warn(`⚠  ${src.label}: could not reach Sanity (${err.message})`);
      if (!existsSync(out)) {
        await writeFile(out, JSON.stringify(src.empty, null, 2) + "\n");
      }
      continue;
    }

    src.check(result); // throws -> build fails, see catch below

    const count = Array.isArray(result.news)
      ? `${result.news.length} item(s)`
      : result.page
        ? "authored"
        : "not authored yet — using built-in copy";
    console.log(`✓ ${src.label}: ${count}`);

    await writeFile(out, JSON.stringify(result, null, 2) + "\n");
  }

  await downloadImages();

  if (!reachable) {
    console.warn("\n   Building with the last committed content.\n");
  }
}

main().catch((err) => {
  console.error(`\n✖ Content is invalid, refusing to build: ${err.message}\n`);
  process.exit(1);
});
